### PR TITLE
Updated getting started doc

### PR DESCRIPTION
**Pull request by malcmiller**
Updated getting started documentation. 
We've encountered errors due to older versions of prereq tools, so this adds verbiage to specify to update to the latest versions.

### CODE REVIEW

**Review by HadwaAbdelhalem — CHANGES_REQUESTED** [review]

**Review by HadwaAbdelhalem — APPROVED** [review]
LGTM!

**Review by polatengin — COMMENTED** [review]
left a small comment

**Review by hattan — CHANGES_REQUESTED** [review]

**Review by polatengin — APPROVED** [review]
lgtm 👍

**Review by hattan — APPROVED** [review]
lgtm

**Pull request merged**
